### ISSUE TITLE
MacOS M1 Arm64 Build Failure

### ISSUE THREAD

**Issue by PierceLBrooks** [Inochi2D/gitver#1]
Hello! I have found that running the command "dub build --build=release --arch=arm64-apple-macos" for this project yields the following error message:

```
    Starting Performing "release" build using ldc2 for aarch64, arm_hardfloat.
    Building semver 0.3.4: building configuration [library]
ldc2: Unknown command line argument '-preserve-dwarf-line-section=false'.  Try: 'ldc2 --help'
ldc2: Did you mean '--force-dwarf-frame-section=false'?
Error ldc2 failed with exit code 1.
```

Any idea on how to proceed past this point?

**Comment by PierceLBrooks** [comment]
Nevermind, I found a solution and have made that available here...
https://github.com/Inochi2D/gitver/pull/2
:)

**Comment by LunaTheFoxgirl** [comment]
This flag will break a lot of builds. Not sure why that flag doesn't exist for you...

**Comment by PierceLBrooks** [comment]
@LunaTheFoxgirl 's commit at https://github.com/Inochi2D/gitver/commit/f0faefe8a67db2acc93640692e6f1a4336e31b85 resolves this!

**Comment by LunaTheFoxgirl** [comment]
Have pushed it to dub as well if you use dub run

**Comment by PierceLBrooks** [comment]
@LunaTheFoxgirl excellent, that works fine as well now without the need for `dub add-local` beforehand or anything when I test with https://github.com/Inochi2D/inochi2d-c
